#!python3

import subprocess
import sys
import json
from git import Repo

def get_tracked_files(trees):
 paths = []
 for tree in trees:  
  for blob in tree.blobs:
   paths.append(blob.abspath)
  if tree.trees:
   paths.extend(get_tracked_files(tree.trees))
 return paths

if __name__ == "__main__":
    repo = Repo('.')
    branch = repo.active_branch
    tracked_files = get_tracked_files([repo.tree()])

    blames = dict()
    for f in tracked_files:
        blames[f] = dict()
        for commit, lines in repo.blame('HEAD', f):
            author = commit.author.name
            real_lines = [x for x in lines if len(x) > 0]
            try:
                blames[f][author] += len(real_lines)
            except KeyError:
                blames[f][author] = len(real_lines)

    with open('git_contributions.json','w') as f:
        json.dump(blames, f)
